/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author meghanamanish
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    Person person;
    public CreatePersonJPanel(Person p) {
        initComponents();
        person = p;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreatePersonJPanel = new javax.swing.JPanel();
        lblPersonDetails = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblLastNmae = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblMobileNumber = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldAge = new javax.swing.JTextField();
        fieldGender = new javax.swing.JTextField();
        fieldMobileNumber = new javax.swing.JTextField();
        btnPersonDetailsSave = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        CreatePersonJPanel.setBackground(new java.awt.Color(204, 255, 255));

        lblPersonDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPersonDetails.setText("Person Details");

        lblFirstName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblFirstName.setText("First Name");

        lblAge.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAge.setText("Age");

        lblLastNmae.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblLastNmae.setText("Last Name");

        lblGender.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblGender.setText("Gender");

        lblMobileNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMobileNumber.setText("Mobile Number");

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        fieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAgeActionPerformed(evt);
            }
        });

        btnPersonDetailsSave.setText("Save");
        btnPersonDetailsSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonDetailsSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreatePersonJPanelLayout = new javax.swing.GroupLayout(CreatePersonJPanel);
        CreatePersonJPanel.setLayout(CreatePersonJPanelLayout);
        CreatePersonJPanelLayout.setHorizontalGroup(
            CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePersonJPanelLayout.createSequentialGroup()
                .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePersonJPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAge)
                            .addComponent(lblLastNmae)
                            .addComponent(lblGender)
                            .addComponent(lblMobileNumber))
                        .addGap(18, 18, 18)
                        .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldMobileNumber)
                            .addComponent(fieldLastName)
                            .addComponent(fieldAge)
                            .addComponent(fieldGender)))
                    .addGroup(CreatePersonJPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblPersonDetails)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(CreatePersonJPanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblFirstName)
                        .addGap(18, 18, 18)
                        .addComponent(fieldFirstName)))
                .addGap(195, 195, 195))
            .addGroup(CreatePersonJPanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(btnPersonDetailsSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreatePersonJPanelLayout.setVerticalGroup(
            CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePersonJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblPersonDetails)
                .addGap(41, 41, 41)
                .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastNmae)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(fieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreatePersonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobileNumber)
                    .addComponent(fieldMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnPersonDetailsSave)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        add(CreatePersonJPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void fieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAgeActionPerformed

    private void btnPersonDetailsSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonDetailsSaveActionPerformed
        // TODO add your handling code here:
        String firstname = fieldFirstName.getText();
        String Secondname = fieldLastName.getText();
        String Gender = fieldGender.getText();
        String Age = fieldAge.getText();
        String MobileNumber = fieldMobileNumber.getText();
        
        person.setFirstName(firstname);
        person.setLastName(firstname);
        person.setAge(Age);
        person.setGender(Gender);
        person.setMobileNumber(MobileNumber);
        
        JOptionPane.showMessageDialog(this,"SUCCESSFULLY SAVED");
        
        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldGender.setText("");
        fieldAge.setText("");
        fieldMobileNumber.setText("");
        
    }//GEN-LAST:event_btnPersonDetailsSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreatePersonJPanel;
    private javax.swing.JButton btnPersonDetailsSave;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldGender;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldMobileNumber;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastNmae;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblPersonDetails;
    // End of variables declaration//GEN-END:variables
}
