/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.LocalAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author meghanamanish
 */
public class CreateLocalAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateLocalAddressJPanel
     */
    LocalAddress localaddress;
    public CreateLocalAddressJPanel(LocalAddress l) {
        initComponents();
        localaddress = l;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateLocalAddressJPanel = new javax.swing.JPanel();
        lblLocalAddress = new javax.swing.JLabel();
        lblStreetName = new javax.swing.JLabel();
        lblUnitName = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        fieldStreetName = new javax.swing.JTextField();
        fieldUnitName = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldZipcode = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        btnLocalAddressSave = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        CreateLocalAddressJPanel.setBackground(new java.awt.Color(255, 255, 204));

        lblLocalAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblLocalAddress.setText("Local Address");

        lblStreetName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblStreetName.setText("Street Name");

        lblUnitName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUnitName.setText(" Unit Name");

        lblCity.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCity.setText("City");

        lblZipcode.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblZipcode.setText("Zipcode");

        lblState.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblState.setText("State");

        fieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCityActionPerformed(evt);
            }
        });

        fieldZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldZipcodeActionPerformed(evt);
            }
        });

        btnLocalAddressSave.setText("Save");
        btnLocalAddressSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalAddressSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateLocalAddressJPanelLayout = new javax.swing.GroupLayout(CreateLocalAddressJPanel);
        CreateLocalAddressJPanel.setLayout(CreateLocalAddressJPanelLayout);
        CreateLocalAddressJPanelLayout.setHorizontalGroup(
            CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLocalAddressJPanelLayout.createSequentialGroup()
                .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(CreateLocalAddressJPanelLayout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblStreetName)
                                .addGroup(CreateLocalAddressJPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCity)
                                        .addComponent(lblUnitName)
                                        .addComponent(lblZipcode)
                                        .addComponent(lblState))))
                            .addGap(18, 18, 18)
                            .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldState)
                                .addComponent(fieldStreetName, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(fieldUnitName)
                                .addComponent(fieldCity)
                                .addComponent(fieldZipcode)))
                        .addGroup(CreateLocalAddressJPanelLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(lblLocalAddress)))
                    .addGroup(CreateLocalAddressJPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnLocalAddressSave)))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        CreateLocalAddressJPanelLayout.setVerticalGroup(
            CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLocalAddressJPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblLocalAddress)
                .addGap(47, 47, 47)
                .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetName)
                    .addComponent(fieldStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitName)
                    .addComponent(fieldUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipcode)
                    .addComponent(fieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(CreateLocalAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnLocalAddressSave)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        add(CreateLocalAddressJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCityActionPerformed

    private void fieldZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldZipcodeActionPerformed

    private void btnLocalAddressSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalAddressSaveActionPerformed
        // TODO add your handling code here:
        String streetname = fieldStreetName.getText();
        String unitname = fieldUnitName.getText();
        String state = fieldState.getText();
        String city = fieldCity.getText();
        String zipcode = fieldZipcode.getText();
        
        localaddress.getCity();
        localaddress.getState();
        localaddress.getStreetName();
        localaddress.getUniName();
        localaddress.getZipcode();
        
        JOptionPane.showMessageDialog(this,"SUCCESSFULLY SAVED");
        
        fieldStreetName.setText("");
        fieldUnitName.setText("");
        fieldState.setText("");
        fieldCity.setText("");
        fieldZipcode.setText("");
               
    }//GEN-LAST:event_btnLocalAddressSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateLocalAddressJPanel;
    private javax.swing.JButton btnLocalAddressSave;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitName;
    private javax.swing.JTextField fieldZipcode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblLocalAddress;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JLabel lblZipcode;
    // End of variables declaration//GEN-END:variables
}
