/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.HomeAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author meghanamanish
 */
public class CreateHomeAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateHomeAddressJPanel
     */
    HomeAddress homeaddress;
    public CreateHomeAddressJPanel(HomeAddress h) {
        initComponents();
        homeaddress = h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateHomeAddressJPanel = new javax.swing.JPanel();
        lblStreetName = new javax.swing.JLabel();
        lblUnitName = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        fieldStreetName = new javax.swing.JTextField();
        fieldUnitName = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldZipcode = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        btnHomeAddressSave = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        CreateHomeAddressJPanel.setBackground(new java.awt.Color(204, 204, 255));

        lblStreetName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblStreetName.setText("Street Name");

        lblUnitName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUnitName.setText("Unit Name");

        lblCity.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCity.setText("City");

        lblZipcode.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblZipcode.setText("Zipcode");

        lblState.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblState.setText("State");

        lblHomeAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblHomeAddress.setText("Home Address");

        fieldStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreetNameActionPerformed(evt);
            }
        });

        fieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStateActionPerformed(evt);
            }
        });

        btnHomeAddressSave.setText("Save");
        btnHomeAddressSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeAddressSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateHomeAddressJPanelLayout = new javax.swing.GroupLayout(CreateHomeAddressJPanel);
        CreateHomeAddressJPanel.setLayout(CreateHomeAddressJPanelLayout);
        CreateHomeAddressJPanelLayout.setHorizontalGroup(
            CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateHomeAddressJPanelLayout.createSequentialGroup()
                .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateHomeAddressJPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lblHomeAddress))
                    .addGroup(CreateHomeAddressJPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUnitName)
                            .addComponent(lblStreetName)
                            .addComponent(lblCity)
                            .addComponent(lblZipcode)
                            .addComponent(lblState))
                        .addGap(18, 18, 18)
                        .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldStreetName, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(fieldUnitName)
                            .addComponent(fieldCity)
                            .addComponent(fieldZipcode)
                            .addComponent(fieldState)))
                    .addGroup(CreateHomeAddressJPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnHomeAddressSave)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        CreateHomeAddressJPanelLayout.setVerticalGroup(
            CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateHomeAddressJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHomeAddress)
                .addGap(36, 36, 36)
                .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetName)
                    .addComponent(fieldStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitName)
                    .addComponent(fieldUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipcode)
                    .addComponent(fieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateHomeAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblState)
                    .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnHomeAddressSave)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        add(CreateHomeAddressJPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStateActionPerformed

    private void fieldStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetNameActionPerformed

    private void btnHomeAddressSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeAddressSaveActionPerformed
        // TODO add your handling code here:
        String streetname = fieldStreetName.getText();
        String unitname = fieldUnitName.getText();
        String city = fieldCity.getText();
        String zipcode = fieldZipcode.getText();
        String state = fieldState.getText();
        
        homeaddress.setCity(city);
        homeaddress.setState(state);
        homeaddress.setStreetName(streetname);
        homeaddress.setUniName(unitname);
        homeaddress.setZipcode(zipcode);
        
        JOptionPane.showMessageDialog(this, "SUCCESSFULLY SAVED");
        
        fieldStreetName.setText("");
        fieldUnitName.setText("");
        fieldCity.setText("");
        fieldZipcode.setText("");
        fieldState.setText("");
    }//GEN-LAST:event_btnHomeAddressSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateHomeAddressJPanel;
    private javax.swing.JButton btnHomeAddressSave;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitName;
    private javax.swing.JTextField fieldZipcode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JLabel lblZipcode;
    // End of variables declaration//GEN-END:variables
}
