/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.LocalAddress;

/**
 *
 * @author meghanamanish
 */
public class ViewLocalAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLocalAddressJPanel
     */
    LocalAddress localaddress;
    public ViewLocalAddressJPanel(LocalAddress l) {
        initComponents();
        localaddress = l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCity = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        fieldStreetName = new javax.swing.JTextField();
        fieldUnitName = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldZipcode = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        lblStreetName = new javax.swing.JLabel();
        lblUnitName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));

        lblCity.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCity.setText("City");

        lblZipcode.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblZipcode.setText("Zipcode");

        lblState.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblState.setText("State");

        lblHomeAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblHomeAddress.setText("Home Address");

        fieldStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreetNameActionPerformed(evt);
            }
        });

        fieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStateActionPerformed(evt);
            }
        });

        lblStreetName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblStreetName.setText("Street Name");

        lblUnitName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUnitName.setText("Unit Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUnitName)
                    .addComponent(lblStreetName)
                    .addComponent(lblCity)
                    .addComponent(lblZipcode)
                    .addComponent(lblState))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(lblHomeAddress)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblHomeAddress)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreetName))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitName)
                    .addComponent(fieldUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(fieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipcode)
                    .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetNameActionPerformed

    private void fieldStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitName;
    private javax.swing.JTextField fieldZipcode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JLabel lblZipcode;
    // End of variables declaration//GEN-END:variables
}
