/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.HomeAddress;

/**
 *
 * @author meghanamanish
 */
public class ViewHomeAddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHomeAddressJPanel
     */
    HomeAddress homeaddress;
    public ViewHomeAddressJPanel(HomeAddress h) {
        initComponents();
        homeaddress = h;
        display();
    }
  private void display() {
  fieldCity.setText(homeaddress.getCity());
  fieldState.setText(homeaddress.getState());
  fieldStreetName.setText(homeaddress.getStreetName());
  fieldUnitName.setText(homeaddress.getUniName());
  fieldZipcode.setText(homeaddress.getZipcode());
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCity = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        fieldStreetName = new javax.swing.JTextField();
        fieldUnitName = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldZipcode = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        lblStreetName = new javax.swing.JLabel();
        lblUnitName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        lblCity.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCity.setText("City");

        lblZipcode.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblZipcode.setText("Zipcode");

        lblState.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblState.setText("State");

        lblHomeAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblHomeAddress.setText("Home Address");

        fieldStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreetNameActionPerformed(evt);
            }
        });

        fieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStateActionPerformed(evt);
            }
        });

        lblStreetName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblStreetName.setText("Street Name");

        lblUnitName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUnitName.setText("Unit Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblZipcode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUnitName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStreetName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblState, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldStreetName, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(fieldUnitName)
                            .addComponent(fieldZipcode)
                            .addComponent(fieldState)
                            .addComponent(fieldCity))
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHomeAddress)
                        .addGap(203, 203, 203))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHomeAddress)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreetName))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitName)
                    .addComponent(fieldUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(fieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipcode)
                    .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetNameActionPerformed

    private void fieldStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitName;
    private javax.swing.JTextField fieldZipcode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JLabel lblZipcode;
    // End of variables declaration//GEN-END:variables

  
}
