/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.BankAccount;

/**
 *
 * @author meghanamanish
 */
public class ViewBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBankAccountJPanel
     */
    BankAccount bankaccount;
    public ViewBankAccountJPanel(BankAccount b) {
        initComponents();
        bankaccount = b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldEmail = new javax.swing.JTextField();
        fieldMobileNumber = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fieldCreditAmount = new javax.swing.JTextField();
        lblPersonName = new javax.swing.JLabel();
        fieldDebitAmount = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblMobileNumber = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblCreditAmount = new javax.swing.JLabel();
        lblDebitAmount = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));

        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });

        fieldMobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMobileNumberActionPerformed(evt);
            }
        });

        fieldAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAccountTypeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Bank Account");

        fieldCreditAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCreditAmountActionPerformed(evt);
            }
        });

        lblPersonName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPersonName.setText("Person Name");

        fieldDebitAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDebitAmountActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmail.setText("Email id");

        lblMobileNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMobileNumber.setText("Mobile Number");

        lblAccountType.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAccountType.setText("Account Type");

        lblCreditAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCreditAmount.setText("Credit Amount");

        lblDebitAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblDebitAmount.setText("Debit Amount");

        fieldPersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMobileNumber)
                                        .addComponent(lblPersonName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAccountType, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblEmail))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDebitAmount)
                                        .addComponent(lblCreditAmount))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldPersonName, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(fieldEmail)
                                .addComponent(fieldMobileNumber)
                                .addComponent(fieldAccountType)
                                .addComponent(fieldCreditAmount)
                                .addComponent(fieldDebitAmount)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel1)))
                    .addContainerGap(222, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jLabel1)
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPersonName)
                        .addComponent(fieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMobileNumber)
                        .addComponent(fieldMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAccountType))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCreditAmount))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDebitAmount)
                        .addComponent(fieldDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(168, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    private void fieldMobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMobileNumberActionPerformed

    private void fieldAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAccountTypeActionPerformed

    private void fieldCreditAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCreditAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCreditAmountActionPerformed

    private void fieldDebitAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDebitAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDebitAmountActionPerformed

    private void fieldPersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldCreditAmount;
    private javax.swing.JTextField fieldDebitAmount;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldMobileNumber;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblCreditAmount;
    private javax.swing.JLabel lblDebitAmount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblPersonName;
    // End of variables declaration//GEN-END:variables
}
